In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(lista)

list

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [16]:
arr[::3]

array([1, 4, 7])

In [17]:
arr[-1]

9

In [23]:
matriz[1:,0:2]

TypeError: list indices must be integers or slices, not tuple